# Generated by Django 3.1.7 on 2021-05-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper', models.TextField()),
                ('destination', models.TextField()),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='no',
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='middlename',
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(max_length=50),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('orderDate', models.DateField()),
                ('payDate', models.DateField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.customer')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('price', models.BigIntegerField()),
                ('inStock', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('image', models.TextField()),
                ('order', models.ManyToManyField(to='Bookstore.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('price', models.BigIntegerField()),
                ('inStock', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('image', models.TextField()),
                ('order', models.ManyToManyField(to='Bookstore.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('price', models.BigIntegerField()),
                ('inStock', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('image', models.TextField()),
                ('order', models.ManyToManyField(to='Bookstore.Order')),
            ],
        ),
    ]
