# Generated by Django 3.1.7 on 2021-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_cart_cart_item_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payDate',
            field=models.DateField(null=True),
        ),
    ]
