# Generated by Django 3.1.7 on 2021-05-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0002_auto_20210524_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
