# Generated by Django 3.2.3 on 2021-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0003_auto_20210329_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='no',
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='middlename',
        ),
    ]
