# Generated by Django 3.1.7 on 2021-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_auto_20210524_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderEmail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
