# Generated by Django 3.2.3 on 2021-05-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0004_auto_20210522_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(max_length=50),
        ),
    ]
