# Generated by Django 3.1.7 on 2021-05-24 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bookstore', '0005_order_orderemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='order',
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='order',
        ),
        migrations.RemoveField(
            model_name='electronic',
            name='order',
        ),
        migrations.CreateModel(
            name='electronics_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('electronics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.electronic')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.order')),
            ],
        ),
        migrations.CreateModel(
            name='clothes_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.clothe')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.order')),
            ],
        ),
        migrations.CreateModel(
            name='book_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookstore.order')),
            ],
        ),
    ]
